test_that("build_tab1 panel A reproduces Tab1 sheet 2022-2025 + growth row", {
  agg <- compute_data_sec_agg(extract_data_sec_all())
  bci_x <- extract_billionaires_ca_inctax()
  ftb <- extract_ftb_b4a()
  b <- compute_billionaires_ca_inctax(agg, bci_x, ftb)
  top4 <- extract_data_sec_top4()
  srs_raw <- extract_shortrunseries()
  srs_r <- compute_shortrunseries(agg, top4, b, srs_raw)
  lrs <- extract_longrunseries()
  tab1 <- build_tab1(agg, srs_r, lrs)

  pa <- attr(tab1, "panel_a")
  # Pull the Tab1 sheet's panel A cells (rows 6..10, cols B..H)
  xl <- read_sheet("Tab1", range = "B6:H10")

  expect_equal(pa$n_billionaires[1:4],   xl$A[1:4], tolerance = 1e-6)
  expect_equal(pa$wealth_b[1:4],         xl$B[1:4], tolerance = 1e-2)
  expect_equal(pa$annual_growth[2:4],    xl$C[2:4], tolerance = 1e-4)
  expect_equal(pa$fraction_public[1:4],  xl$D[1:4], tolerance = 1e-4)
  expect_equal(pa$top4_wealth_b[1:4],    xl$E[1:4], tolerance = 1e-2)
  expect_equal(pa$ca_gdp_b[1:4],         xl$F[1:4], tolerance = 1e-2)
  expect_equal(pa$wealth_per_gdp[1:4],   xl$G[1:4], tolerance = 1e-4)
  # Growth row (row 10 of Tab1 sheet) — B, E, F columns only
  expect_equal(pa$wealth_b[5],           xl$B[5], tolerance = 1e-4)
  expect_equal(pa$top4_wealth_b[5],      xl$E[5], tolerance = 1e-4)
  expect_equal(pa$ca_gdp_b[5],           xl$F[5], tolerance = 1e-4)
})

test_that("build_tab1 panel B reproduces Tab1 sheet 1982 + 2025 + ratios + annualized", {
  agg <- compute_data_sec_agg(extract_data_sec_all())
  bci_x <- extract_billionaires_ca_inctax()
  ftb <- extract_ftb_b4a()
  b <- compute_billionaires_ca_inctax(agg, bci_x, ftb)
  top4 <- extract_data_sec_top4()
  srs_raw <- extract_shortrunseries()
  srs_r <- compute_shortrunseries(agg, top4, b, srs_raw)
  lrs <- extract_longrunseries()
  tab1 <- build_tab1(agg, srs_r, lrs)

  pb <- attr(tab1, "panel_b")
  # Tab1 panel B is at rows 14..17, cols C..H
  xl <- read_sheet("Tab1", range = "C14:H17")
  expect_equal(pb$families_top0002_k,   xl$A, tolerance = 1e-3)
  expect_equal(pb$wealth_top0002_b,     xl$B, tolerance = 1e-2)
  expect_equal(pb$wealth_per_family_b,  xl$C, tolerance = 1e-3)
  expect_equal(pb$n_ca_families_m,      xl$D, tolerance = 1e-3)
  expect_equal(pb$ca_gdp_2025dollars_b, xl$E, tolerance = 1e-1)
  expect_equal(pb$gdp_per_family_k,     xl$F, tolerance = 1)
})

test_that("build_tab2 reproduces Tab2 sheet 2019-2025 + average row", {
  agg <- compute_data_sec_agg(extract_data_sec_all())
  bci_x <- extract_billionaires_ca_inctax()
  ftb <- extract_ftb_b4a()
  b <- compute_billionaires_ca_inctax(agg, bci_x, ftb)
  top4 <- extract_data_sec_top4()
  tab2 <- build_tab2(agg, b, top4)
  p <- attr(tab2, "panel")
  xl <- read_sheet("Tab2", range = "B7:H14")  # cols B..H, rows 7..14

  expect_equal(p$wealth_b,                  xl$A, tolerance = 1e-2)
  expect_equal(p$ca_inctax_b,               xl$B, tolerance = 1e-3)
  expect_equal(p$ca_inctax_per_wealth,      xl$C, tolerance = 1e-5)
  expect_equal(p$top4_company_wealth_b,     xl$E, tolerance = 1e-2)
  expect_equal(p$top4_ca_inctax_b,          xl$F, tolerance = 1e-3)
  expect_equal(p$top4_ca_inctax_per_wealth, xl$G, tolerance = 1e-5)
})

test_that("build_tab2 renders to non-empty HTML and LaTeX", {
  agg <- compute_data_sec_agg(extract_data_sec_all())
  bci_x <- extract_billionaires_ca_inctax()
  ftb <- extract_ftb_b4a()
  b <- compute_billionaires_ca_inctax(agg, bci_x, ftb)
  top4 <- extract_data_sec_top4()
  tab2 <- build_tab2(agg, b, top4)
  html <- as.character(gt::as_raw_html(tab2))
  expect_gt(nchar(html), 1000)
  expect_true(grepl("Income Tax Paid by California Billionaires", html))
  tex <- as.character(gt::as_latex(tab2))
  expect_gt(nchar(tex), 200)
})

test_that("build_tab1 renders to non-empty HTML and LaTeX", {
  agg <- compute_data_sec_agg(extract_data_sec_all())
  bci_x <- extract_billionaires_ca_inctax()
  ftb <- extract_ftb_b4a()
  b <- compute_billionaires_ca_inctax(agg, bci_x, ftb)
  top4 <- extract_data_sec_top4()
  srs_raw <- extract_shortrunseries()
  srs_r <- compute_shortrunseries(agg, top4, b, srs_raw)
  lrs <- extract_longrunseries()
  tab1 <- build_tab1(agg, srs_r, lrs)

  html <- as.character(gt::as_raw_html(tab1))
  expect_gt(nchar(html), 1000)
  expect_true(grepl("Wealth Growth of California Billionaires", html))
  expect_true(grepl("Recent nominal wealth growth", html))
  expect_true(grepl("Long-term real wealth growth", html))

  tex <- as.character(gt::as_latex(tab1))
  expect_gt(nchar(tex), 200)
  expect_true(grepl("\\\\begin\\{longtable\\}|\\\\begin\\{tabular\\}", tex))
})
